version: '3'

services:
  cbioportal-local:
    domainname: sodnycu
    restart: unless-stopped
    image: ${DOCKER_IMAGE_CBIOPORTAL}
    container_name: cbioportal-container-local
    environment:
      SHOW_DEBUG_INFO: "true"
    ports:
      - "80:80"
    volumes:
     - study:/study/
     - config:/config/
    depends_on:
     - cbioportal-database
     - cbioportal-session-local
    networks:
     - cbio-net-local
    command: /bin/sh -c "cp /config/portal.properties-localmysql /cbioportal/portal.properties && java -Xms2g -Xmx4g -Dauthenticate=noauthsessionservice -Dsession.service.url=http://cbioportal-session:5000/api/sessions/my_portal/ -jar webapp-runner.jar -AmaxHttpHeaderSize=16384 -AconnectionTimeout=20000 --enable-compression /cbioportal-webapp --port 80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 5G
        reservations:
          cpus: '0.5'
          memory: 2G
  cbioportal-database:
    restart: unless-stopped
    image: acienv.azurecr.io/mysql:5.7
    container_name: cbioportal-database-container
    environment:
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio_user
      MYSQL_PASSWORD: somepassword
      MYSQL_ROOT_PASSWORD: somepassword
    volumes:
     - data:/data
     - mysqldata:/var/lib/mysql
    networks:
     - cbio-net-local
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 2G
  cbioportal-session-local:
    restart: unless-stopped
    image: ${DOCKER_IMAGE_SESSION_SERVICE}
    container_name: cbioportal-session-container-local
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal-session-database:27017/session-service
    depends_on:
      - cbioportal-session-database-local
    networks:
      - cbio-net-local
    deploy:
      resources:
        limits:
          cpus: '0.1'
        reservations:
          cpus: '0.1'
  cbioportal-session-database-local:
    restart: unless-stopped
    image: mongo:3.7.9
    container_name: cbioportal-session-database-container-local
    environment:
      MONGO_INITDB_DATABASE: session_service
    networks:
      - cbio-net-local
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 2G

networks:
  cbio-net-local: 
  
volumes:
  config:
    driver: azure_file
    driver_opts:
      share_name: config
      storage_account_name: cbioportalstorage
  study:
    driver: azure_file
    driver_opts:
      share_name: study
      storage_account_name: cbioportalstorage
  data:
    driver: azure_file
    driver_opts:
      share_name: data
      storage_account_name: cbioportalstorage
  mysqldata:
    driver: azure_file
    driver_opts:
      share_name: mysqldatalocal
      storage_account_name: cbioportalstorage
  mongodata:
    driver: azure_file
    driver_opts:
      share_name: mongodata
      storage_account_name: cbioportalstorage
